export const actionTypes = {
  ADD_RULE: 'TEST_APP/FLOW_PAGE/ADD_RULE',
  CHANGE_RULE: 'TEST_APP/FLOW_PAGE/CHANGE_RULE',
  CHANGE_CONTENT: 'TEST_APP/FLOW_PAGE/CHANGE_CONTENT',
  EXECUTE: 'TEST_APP/FLOW_PAGE/EXECUTE',
  EXECUTE_END: 'TEST_APP/FLOW_PAGE/EXECUTE_END',
};

export const key = 'FLOW_PAGE';
